// ui actions
export const LOADING_FILE_LIST = 'LOADING_FILE_LIST'
export const LOADED_FILE_LIST = 'LOADED_FILE_LIST'
export const FILE_LOADED = 'FILE_LOADED'
export const FILE_SAVED = 'FILE_SAVED'
export const NEW_FILE = 'NEW_FILE'
export const EDIT_FILENAME = 'EDIT_FILENAME'
export const CHANGE_CURRENT_VIEW = 'CHANGE_CURRENT_VIEW'
export const CHANGE_ORIENTATION = 'CHANGE_ORIENTATION'
export const CHANGE_CURRENT_TIMELINE = 'CHANGE_CURRENT_TIMELINE'
export const RESET = 'RESET'
export const SET_CHARACTER_SORT = 'SET_CHARACTER_SORT'
export const SET_PLACE_SORT = 'SET_PLACE_SORT'
export const SET_NOTE_SORT = 'SET_NOTE_SORT'
export const SET_CHARACTER_FILTER = 'SET_CHARACTER_FILTER'
export const SET_PLACE_FILTER = 'SET_PLACE_FILTER'
export const SET_NOTE_FILTER = 'SET_NOTE_FILTER'
export const NAVIGATE_TO_BOOK_TIMELINE = 'NAVIGATE_TO_BOOK_TIMELINE'
export const EXPAND_TIMELINE = 'EXPAND_TIMELINE'
export const COLLAPSE_TIMELINE = 'COLLAPSE_TIMELINE'
export const SET_TIMELINE_FILTER = 'SET_TIMELINE_FILTER'
export const CLEAR_TEMPLATE_FROM_TIMELINE = 'CLEAR_TEMPLATE_FROM_TIMELINE'
export const RESET_TIMELINE = 'RESET_TIMELINE'
export const RECORD_SCROLL_POSITION = 'RECORD_SCROLL_POSITION'
export const OPEN_ATTRIBUTES_DIALOG = 'OPEN_ATTRIBUTES_DIALOG'
export const CLOSE_ATTRIBUTES_DIALOG = 'CLOSE_ATTRIBUTES_DIALOG'
export const SET_TIMELINE_SIZE = 'SET_TIMELINE_SIZE'
export const SET_OUTLINE_FILTER = 'SET_OUTLINE_FILTER'
export const LOAD_FILE = 'LOAD_FILE'

// beat actions
export const ADD_BEAT = 'ADD_BEAT'
export const EDIT_BEAT_TITLE = 'EDIT_BEAT_TITLE'
export const REORDER_BEATS = 'REORDER_BEATS'
export const DELETE_BEAT = 'DELETE_BEAT'
export const AUTO_SORT_BEAT = 'AUTO_SORT_BEAT'
export const INSERT_BEAT = 'INSERT_BEAT'
export const EXPAND_BEAT = 'EXPAND_BEAT'
export const COLLAPSE_BEAT = 'COLLAPSE_BEAT'
export const LOAD_BEATS = 'LOAD_BEATS'

// card actions
export const ADD_CARD = 'ADD_CARD'
export const ADD_CARD_IN_BEAT = 'ADD_CARD_IN_BEAT'
export const EDIT_CARD_DETAILS = 'EDIT_CARD_DETAILS'
export const EDIT_CARD_TEMPLATE_ATTRIBUTE = 'EDIT_CARD_TEMPLATE_ATTRIBUTE'
export const EDIT_CARD_COORDINATES = 'EDIT_CARD_COORDINATES'
export const DELETE_CARD = 'DELETE_CARD'
export const CHANGE_LINE = 'CHANGE_STORYLINE'
export const CHANGE_BEAT = 'CHANGE_BEAT'
export const CHANGE_BOOK = 'CHANGE_BOOK'
export const REORDER_CARDS_WITHIN_LINE = 'REORDER_CARDS_WITHIN_LINE'
export const REORDER_CARDS_IN_BEAT = 'REORDER_CARDS_IN_BEAT'
export const ATTACH_CHARACTER_TO_CARD = 'ATTACH_CHARACTER_TO_CARD'
export const ATTACH_PLACE_TO_CARD = 'ATTACH_PLACE_TO_CARD'
export const ATTACH_TAG_TO_CARD = 'ATTACH_TAG_TO_CARD'
export const REMOVE_CHARACTER_FROM_CARD = 'REMOVE_CHARACTER_FROM_CARD'
export const REMOVE_PLACE_FROM_CARD = 'REMOVE_PLACE_FROM_CARD'
export const REMOVE_TAG_FROM_CARD = 'REMOVE_TAG_FROM_CARD'
export const LOAD_CARDS = 'LOAD_CARDS'
export const ADD_TEMPLATE_TO_CARD = 'ADD_TEMPLATE_TO_CARD'
export const REMOVE_TEMPLATE_FROM_CARD = 'REMOVE_TEMPLATE_FROM_CARD'
export const DUPLICATE_CARD = 'DUPLICATE_CARD'
export const MOVE_CARD_TO_BOOK = 'MOVE_CARD_TO_BOOK'

// line actions
export const ADD_LINE = 'ADD_STORYLINE'
export const ADD_LINE_WITH_TITLE = 'ADD_LINE_WITH_TITLE'
export const ADD_LINES_FROM_TEMPLATE = 'ADD_LINES_FROM_TEMPLATE'
export const EDIT_LINE = 'EDIT_LINE'
export const EDIT_LINE_TITLE = 'EDIT_STORYLINE_TITLE'
export const EDIT_LINE_COLOR = 'EDIT_STORYLINE_COLOR'
export const REORDER_LINES = 'REORDER_STORYLINES'
export const DELETE_LINE = 'DELETE_STORYLINE'
export const EXPAND_LINE = 'EXPAND_LINE'
export const COLLAPSE_LINE = 'COLLAPSE_LINE'
export const DUPLICATE_LINE = 'DUPLICATE_LINE'
export const LOAD_LINES = 'LOAD_LINES'
export const MOVE_LINE = 'MOVE_LINE'

// places actions
export const ADD_PLACE = 'ADD_PLACE'
export const ADD_PLACE_WITH_VALUES = 'ADD_PLACE_WITH_VALUES'
export const EDIT_PLACE = 'EDIT_PLACE'
export const EDIT_PLACE_TEMPLATE_ATTRIBUTE = 'EDIT_PLACE_TEMPLATE_ATTRIBUTE'
export const DELETE_PLACE = 'DELETE_PLACE'
export const ATTACH_TAG_TO_PLACE = 'ATTACH_TAG_TO_PLACE'
export const ATTACH_BOOK_TO_PLACE = 'ATTACH_BOOK_TO_PLACE'
export const REMOVE_TAG_FROM_PLACE = 'REMOVE_TAG_FROM_PLACE'
export const REMOVE_BOOK_FROM_PLACE = 'REMOVE_BOOK_FROM_PLACE'
export const LOAD_PLACES = 'LOAD_PLACES'

// tags actions
export const ADD_TAG = 'ADD_TAG'
export const ADD_TAG_WITH_VALUES = 'ADD_TAG_WITH_VALUES'
export const ADD_CREATED_TAG = 'ADD_CREATED_TAG'
export const EDIT_TAG = 'EDIT_TAG'
export const CHANGE_TAG_COLOR = 'CHANGE_TAG_COLOR'
export const DELETE_TAG = 'DELETE_TAG'
export const LOAD_TAGS = 'LOAD_TAGS'

// characters actions
export const ADD_CHARACTER = 'ADD_CHARACTER'
export const ADD_CHARACTER_WITH_TEMPLATE = 'ADD_CHARACTER_WITH_TEMPLATE'
export const ADD_CHARACTER_WITH_VALUES = 'ADD_CHARACTER_WITH_VALUES'
export const EDIT_CHARACTER = 'EDIT_CHARACTER'
export const EDIT_CHARACTER_TEMPLATE_ATTRIBUTE = 'EDIT_CHARACTER_TEMPLATE_ATTRIBUTE'
export const DELETE_CHARACTER = 'DELETE_CHARACTER'
export const ATTACH_TAG_TO_CHARACTER = 'ATTACH_TAG_TO_CHARACTER'
export const ATTACH_BOOK_TO_CHARACTER = 'ATTACH_BOOK_TO_CHARACTER'
export const REMOVE_TAG_FROM_CHARACTER = 'REMOVE_TAG_FROM_CHARACTER'
export const REMOVE_BOOK_FROM_CHARACTER = 'REMOVE_BOOK_FROM_CHARACTER'
export const LOAD_CHARACTERS = 'LOAD_CHARACTERS'
export const ADD_TEMPLATE_TO_CHARACTER = 'ADD_TEMPLATE_TO_CHARACTER'
export const REMOVE_TEMPLATE_FROM_CHARACTER = 'REMOVE_TEMPLATE_FROM_CHARACTER'

// notes actions
export const ADD_NOTE = 'ADD_NOTE'
export const EDIT_NOTE = 'EDIT_NOTE'
export const EDIT_NOTE_TEMPLATE_ATTRIBUTE = 'EDIT_NOTE_TEMPLATE_ATTRIBUTE'
export const DELETE_NOTE = 'DELETE_NOTE'
export const ATTACH_CHARACTER_TO_NOTE = 'ATTACH_CHARACTER_TO_NOTE'
export const ATTACH_PLACE_TO_NOTE = 'ATTACH_PLACE_TO_NOTE'
export const ATTACH_TAG_TO_NOTE = 'ATTACH_TAG_TO_NOTE'
export const ATTACH_BOOK_TO_NOTE = 'ATTACH_BOOK_TO_NOTE'
export const REMOVE_CHARACTER_FROM_NOTE = 'REMOVE_CHARACTER_FROM_NOTE'
export const REMOVE_PLACE_FROM_NOTE = 'REMOVE_PLACE_FROM_NOTE'
export const REMOVE_TAG_FROM_NOTE = 'REMOVE_TAG_FROM_NOTE'
export const REMOVE_BOOK_FROM_NOTE = 'REMOVE_BOOK_FROM_NOTE'
export const SET_NOTES_SEARCH_TERM = 'SET_NOTES_SEARCH_TERM'
export const SET_CHARACTERS_SEARCH_TERM = 'SET_CHARACTERS_SEARCH_TERM'
export const SET_PLACES_SEARCH_TERM = 'SET_PLACES_SEARCH_TERM'
export const SET_TAGS_SEARCH_TERM = 'SET_TAGS_SEARCH_TERM'
export const SET_OUTLINE_SEARCH_TERM = 'SET_OUTLINE_SEARCH_TERM'
export const LOAD_NOTES = 'LOAD_NOTES'

// custom attribute actions
export const ADD_CHARACTER_ATTRIBUTE = 'ADD_CHARACTER_ATTRIBUTE'
export const ADD_PLACES_ATTRIBUTE = 'ADD_PLACES_ATTRIBUTE'
export const ADD_CARDS_ATTRIBUTE = 'ADD_CARDS_ATTRIBUTE'
export const ADD_LINES_ATTRIBUTE = 'ADD_LINES_ATTRIBUTE'
export const ADD_NOTES_ATTRIBUTE = 'ADD_NOTES_ATTRIBUTE'

export const REMOVE_CHARACTER_ATTRIBUTE = 'REMOVE_CHARACTER_ATTRIBUTE'
export const REMOVE_PLACES_ATTRIBUTE = 'REMOVE_PLACES_ATTRIBUTE'
export const REMOVE_CARDS_ATTRIBUTE = 'REMOVE_CARDS_ATTRIBUTE'
export const REMOVE_LINES_ATTRIBUTE = 'REMOVE_LINES_ATTRIBUTE'
export const REMOVE_NOTES_ATTRIBUTE = 'REMOVE_NOTES_ATTRIBUTE'

export const EDIT_CHARACTER_ATTRIBUTE = 'EDIT_CHARACTER_ATTRIBUTE'
export const EDIT_PLACES_ATTRIBUTE = 'EDIT_PLACES_ATTRIBUTE'
export const EDIT_CARDS_ATTRIBUTE = 'EDIT_CARDS_ATTRIBUTE'
export const EDIT_LINES_ATTRIBUTE = 'EDIT_LINES_ATTRIBUTE'
export const EDIT_NOTES_ATTRIBUTE = 'EDIT_NOTES_ATTRIBUTE'

export const REORDER_CHARACTER_ATTRIBUTE = 'REORDER_CHARACTER_ATTRIBUTE'
export const REORDER_PLACES_ATTRIBUTE = 'REORDER_PLACES_ATTRIBUTE'
export const REORDER_CARDS_ATTRIBUTE = 'REORDER_CARDS_ATTRIBUTE'
export const REORDER_LINES_ATTRIBUTE = 'REORDER_LINES_ATTRIBUTE'
export const REORDER_NOTES_ATTRIBUTE = 'REORDER_NOTES_ATTRIBUTE'

export const LOAD_CUSTOM_ATTRIBUTES = 'LOAD_CUSTOM_ATTRIBUTES'

// image actions
export const ADD_IMAGE = 'ADD_IMAGE'
export const RENAME_IMAGE = 'RENAME_IMAGE'
export const DELETE_IMAGE = 'DELETE_IMAGE'
export const LOAD_IMAGES = 'LOAD_IMAGES'

// series actions
export const EDIT_SERIES = 'EDIT_SERIES'
export const LOAD_SERIES = 'LOAD_SERIES'

// book actions
export const ADD_BOOK = 'ADD_BOOK'
export const ADD_BOOK_FROM_TEMPLATE = 'ADD_BOOK_FROM_TEMPLATE'
export const EDIT_BOOK = 'EDIT_BOOK'
export const DELETE_BOOK = 'DELETE_BOOK'
export const REORDER_BOOKS = 'REORDER_BOOKS'
export const LOAD_BOOKS = 'LOAD_BOOKS'

// category actions
export const ADD_CHARACTER_CATEGORY = 'ADD_CHARACTER_CATEGORY'
export const DELETE_CHARACTER_CATEGORY = 'DELETE_CHARACTER_CATEGORY'
export const UPDATE_CHARACTER_CATEGORY = 'UPDATE_CHARACTER_CATEGORY'
export const REORDER_CHARACTER_CATEGORY = 'REORDER_CHARACTER_CATEGORY'
export const ADD_NOTE_CATEGORY = 'ADD_NOTE_CATEGORY'
export const DELETE_NOTE_CATEGORY = 'DELETE_NOTE_CATEGORY'
export const UPDATE_NOTE_CATEGORY = 'UPDATE_NOTE_CATEGORY'
export const REORDER_NOTE_CATEGORY = 'REORDER_NOTE_CATEGORY'
export const ADD_TAG_CATEGORY = 'ADD_TAG_CATEGORY'
export const DELETE_TAG_CATEGORY = 'DELETE_TAG_CATEGORY'
export const UPDATE_TAG_CATEGORY = 'UPDATE_TAG_CATEGORY'
export const REORDER_TAG_CATEGORY = 'REORDER_TAG_CATEGORY'
export const ADD_PLACE_CATEGORY = 'ADD_PLACE_CATEGORY'
export const DELETE_PLACE_CATEGORY = 'DELETE_PLACE_CATEGORY'
export const UPDATE_PLACE_CATEGORY = 'UPDATE_PLACE_CATEGORY'
export const REORDER_PLACE_CATEGORY = 'REORDER_PLACE_CATEGORY'
export const LOAD_CATEGORIES = 'LOAD_CATEGORIES'

// hierarchy actions
export const SET_HIERARCHY_LEVELS = 'SET_HIERARCHY_LEVELS'
export const EDIT_HIERARCHY_LEVEL = 'EDIT_HIERARCHY_LEVEL'
export const LOAD_HIERARCHY = 'LOAD_HIERARCHY'

// feature flags
export const SET_FEATURE_FLAG = 'SET_FEATURE_FLAG'
export const UNSET_FEATURE_FLAG = 'UNSET_FEATURE_FLAG'
export const LOAD_FEATURE_FLAGS = 'LOAD_FEATURE_FLAGS'

// tour actions
export const SET_TOUR_FEATURE = 'SET_TOUR_FEATURE'
export const TOUR_NEXT = 'TOUR_NEXT'
export const TOUR_RESTART = 'TOUR_RESTART'
export const LOAD_TOUR = 'LOAD_TOUR'

// error actions
export const PERMISSION_ERROR = 'PERMISSION_ERROR'
export const GENERAL_ERROR = 'GENERAL_ERROR'
export const CLEAR_ERROR = 'CLEAR_ERROR'
export const IMPORT_ERROR = 'IMPORT_ERROR'
export const SAVE_TEMP_FILE_ERROR = 'SAVE_TEMP_FILE_ERROR'
// IMPORTANT: Please keep this up to date(!).  Impacts our ability to
// track actual changes to the content of a file as apposed to system
// data.
export const ERROR_ACTIONS = [
  PERMISSION_ERROR,
  GENERAL_ERROR,
  CLEAR_ERROR,
  IMPORT_ERROR,
  SAVE_TEMP_FILE_ERROR,
]

// permission actions
export const SET_PERMISSION = 'SET_PERMISSION'
// IMPORTANT: Please keep this up to date(!).  Impacts our ability to
// track actual changes to the content of a file as apposed to system
// data.
export const PERMISSION_ACTIONS = [SET_PERMISSION]

// project actions
export const SET_FILE_LIST = 'SET_FILE_LIST'
export const SELECT_FILE = 'SELECT_FILE'
export const SELECT_EMPTY_FILE = 'SELECT_EMPTY_FILE'
export const SET_FILE_LOADED = 'SET_FILE_LOADED'
export const UNSET_FILE_LOADED = 'UNSET_FILE_LOADED'
export const SHOW_LOADER = 'SHOW_LOADER'
export const SET_OFFLINE = 'SET_OFFLINE'
export const SET_RESUMING = 'SET_RESUMING'
export const SET_CHECKING_FOR_OFFLINE_DRIFT = 'SET_CHECKING_FOR_OFFLINE_DRIFT'
export const SET_OVERWRITING_CLOUD_WITH_BACKUP = 'SET_OVERWRITING_CLOUD_WITH_BACKUP'
export const SET_SHOW_RESUME_MESSAGE_DIALOG = 'SET_SHOW_RESUME_MESSAGE_DIALOG'
export const SET_BACKING_UP_OFFLINE_FILE = 'SET_BACKING_UP_OFFLINE_FILE'
// IMPORTANT: Please keep this up to date(!).  Impacts our ability to
// track actual changes to the content of a file as apposed to system
// data.
export const PROJECT_ACTIONS = [
  SET_FILE_LIST,
  SELECT_FILE,
  SELECT_EMPTY_FILE,
  SET_FILE_LOADED,
  UNSET_FILE_LOADED,
  SHOW_LOADER,
  SET_OFFLINE,
  SET_RESUMING,
  SET_CHECKING_FOR_OFFLINE_DRIFT,
  SET_OVERWRITING_CLOUD_WITH_BACKUP,
  SET_SHOW_RESUME_MESSAGE_DIALOG,
  SET_BACKING_UP_OFFLINE_FILE,
]

// client actions
export const SET_USER_ID = 'SET_USER_ID'
export const SET_CLIENT_ID = 'SET_CLIENT_ID'
export const SET_EMAIL_ADDRESS = 'SET_EMAIL_ADDRESS'
export const SET_HAS_PRO = 'SET_HAS_PRO'
export const SET_IS_ON_WEB = 'SET_IS_ON_WEB'
export const SET_CURRENT_APP_STATE = 'SET_CURRENT_APP_STATE'
// IMPORTANT: Please keep this up to date(!).  Impacts our ability to
// track actual changes to the content of a file as apposed to system
// data.
export const CLIENT_ACTIONS = [
  SET_USER_ID,
  SET_CLIENT_ID,
  SET_EMAIL_ADDRESS,
  SET_HAS_PRO,
  SET_IS_ON_WEB,
  SET_CURRENT_APP_STATE,
]

// action actions (for undo)
export const RECORD_LAST_ACTION = 'RECORD_LAST_ACTION'
export const RESET_ACTION_RECORDER = 'RESET_ACTION_RECORDER'
// IMPORTANT: Please keep this up to date(!).  Impacts our ability to
// track actual changes to the content of a file as apposed to system
// data.
export const ACTION_ACTIONS = [RECORD_LAST_ACTION, RESET_ACTION_RECORDER]

// License actions
export const SET_TRIAL_INFO = 'SET_TRIAL_INFO'
export const SET_LICENSE_INFO = 'SET_LICENSE_INFO'
export const SET_PRO_LICENSE_INFO = 'SET_PRO_LICENSE_INFO'
export const RESET_PRO_LICENSE_INFO = 'RESET_PRO_LICENSE_INFO'
export const LICENSE_ACTIONS = [
  SET_TRIAL_INFO,
  SET_LICENSE_INFO,
  SET_PRO_LICENSE_INFO,
  RESET_PRO_LICENSE_INFO,
]

// editor actions

// Known files
export const SET_KNOWN_FILES = 'SET_KNOWN_FILES'
export const KNOWN_FILES_ACTIONS = [SET_KNOWN_FILES]

// Templates
export const SET_TEMPLATES = 'SET_TEMPLATES'
export const SET_CUSTOM_TEMPLATES = 'SET_CUSTOM_TEMPLATES'
export const SET_TEMPLATE_MANIFEST = 'SET_TEMPLATE_MANIFEST'
export const TEMPLATE_ACTIONS = [SET_TEMPLATES, SET_CUSTOM_TEMPLATES, SET_TEMPLATE_MANIFEST]

// Settings
export const SET_EXPORT_SETTINGS = 'SET_EXPORT_SETTINGS'
export const SET_USER_SETTINGS = 'SET_USER_SETTINGS'
export const SET_APP_SETTINGS = 'SET_APP_SETTINGS'
export const SET_DARK_MODE = 'SET_DARK_MODE'
export const SETTINGS_ACTIONS = [
  SET_EXPORT_SETTINGS,
  SET_USER_SETTINGS,
  SET_APP_SETTINGS,
  SET_DARK_MODE,
]

// Backups
export const SET_BACKUP_FOLDERS = 'SET_BACKUP_FOLDERS'
export const BACKUP_ACTIONS = [SET_BACKUP_FOLDERS]

// Application State
export const START_LOADING_FILE_LIST = 'START_LOADING_FILE_LIST'
export const FINISH_LOADING_FILE_LIST = 'FINISH_LOADING_FILE_LIST'
export const START_CREATING_CLOUD_FILE = 'START_CREATING_CLOUD_FILE'
export const FINISH_CREATING_CLOUD_FILE = 'FINISH_CREATING_CLOUD_FILE'
export const START_UPLOADING_FILE_TO_CLOUD = 'START_UPLOADING_FILE_TO_CLOUD'
export const FINISH_UPLOADING_FILE_TO_CLOUD = 'FINISH_UPLOADING_FILE_TO_CLOUD'
export const START_CHECKING_FILE_TO_LOAD = 'START_CHECKING_FILE_TO_LOAD'
export const FINISH_CHECKING_FILE_TO_LOAD = 'FINISH_CHECKING_FILE_TO_LOAD'
export const START_LOADING_FILE = 'START_LOADING_FILE'
export const FINISH_LOADING_FILE = 'FINISH_LOADING_FILE'
export const START_RENAMING_FILE = 'START_RENAMING_FILE'
export const FINISH_RENAMING_FILE = 'FINISH_RENAMING_FILE'
export const START_DELETING_FILE = 'START_DELETING_FILE'
export const FINISH_DELETING_FILE = 'FINISH_DELETING_FILE'
export const START_SAVING_FILE_AS = 'START_SAVING_FILE_AS'
export const FINISH_SAVING_FILE_AS = 'FINISH_SAVING_FILE_AS'
export const START_LOGGING_IN = 'START_LOGGING_IN'
export const FINISH_LOGGING_IN = 'FINISH_LOGGING_IN'
export const START_CHECKING_SESSION = 'START_CHECKING_SESSION'
export const FINISH_CHECKING_SESSION = 'FINISH_CHECKING_SESSION'
export const START_LOADING_A_LICENSE_TYPE = 'START_LOADING_A_LICENSE_TYPE'
export const FINISH_LOADING_A_LICENSE_TYPE = 'FINISH_LOADING_A_LICENSE_TYPE'
export const START_LOADING_A_SETTINGS_TYPE = 'START_LOADING_A_SETTINGS_TYPE'
export const FINISH_LOADING_A_SETTINGS_TYPE = 'FINISH_LOADING_A_SETTINGS_TYPE'
export const ADVANCE_PRO_ONBOARDING = 'ADVANCE_PRO_ONBOARDING'
export const START_ONBOARDING = 'START_ONBOARDING'
export const FINISH_ONBOARDING = 'FINISH_ONBOARDING'
export const START_ONBOARDING_FROM_ROOT = 'START_ONBOARDING_FROM_ROOT'
export const START_IMPORTING_SCRIVENER = 'START_IMPORTING_SCRIVENER'
export const FINISH_IMPORTING_SCRIVENER = 'FINISH_IMPORTING_SCRIVENER'
export const APPLICATION_STATE_ACTIONS = [
  START_LOADING_FILE_LIST,
  FINISH_LOADING_FILE_LIST,
  START_CREATING_CLOUD_FILE,
  FINISH_CREATING_CLOUD_FILE,
  START_UPLOADING_FILE_TO_CLOUD,
  FINISH_UPLOADING_FILE_TO_CLOUD,
  START_CHECKING_FILE_TO_LOAD,
  FINISH_CHECKING_FILE_TO_LOAD,
  START_LOADING_FILE,
  FINISH_LOADING_FILE,
  START_RENAMING_FILE,
  FINISH_RENAMING_FILE,
  START_DELETING_FILE,
  FINISH_DELETING_FILE,
  START_SAVING_FILE_AS,
  FINISH_SAVING_FILE_AS,
  START_LOGGING_IN,
  FINISH_LOGGING_IN,
  START_CHECKING_SESSION,
  FINISH_CHECKING_SESSION,
  START_LOADING_A_LICENSE_TYPE,
  FINISH_LOADING_A_LICENSE_TYPE,
  START_LOADING_A_SETTINGS_TYPE,
  FINISH_LOADING_A_SETTINGS_TYPE,
  ADVANCE_PRO_ONBOARDING,
  START_ONBOARDING,
  FINISH_ONBOARDING,
  START_ONBOARDING_FROM_ROOT,
  START_IMPORTING_SCRIVENER,
  FINISH_IMPORTING_SCRIVENER,
]

// Image Cache
export const CACHE_IMAGE = 'CACHE_IMAGE'
export const IMAGE_CACHE_ACTIONS = [CACHE_IMAGE]

export const SHOW_TOAST_NOTIFICATION = 'SHOW_TOAST_NOTIFICATION'
export const SHOW_MESSAGE = 'SHOW_MESSAGE'
export const DISMISS_MESSAGE = 'DISMISS_MESSAGE'
export const NOTIFICATION_ACTIONS = [SHOW_TOAST_NOTIFICATION, SHOW_MESSAGE, DISMISS_MESSAGE]

export const CLICK_ON_DOM = ['CLICK_ON_DOM']
export const DOM_EVENT_ACTIONS = [CLICK_ON_DOM]
