//ui actions
export const FILE_LOADED = 'FILE_LOADED'
export const FILE_SAVED = 'FILE_SAVED'
export const NEW_FILE = 'NEW_FILE'
export const EDIT_FILENAME = 'EDIT_FILENAME'
export const CHANGE_CURRENT_VIEW = 'CHANGE_CURRENT_VIEW'
export const CHANGE_ORIENTATION = 'CHANGE_ORIENTATION'
export const CHANGE_CURRENT_TIMELINE = 'CHANGE_CURRENT_TIMELINE'
export const RESET = 'RESET'
export const SET_DARK_MODE = 'SET_DARK_MODE'
export const SET_CHARACTER_SORT = 'SET_CHARACTER_SORT'
export const SET_PLACE_SORT = 'SET_PLACE_SORT'
export const SET_NOTE_SORT = 'SET_NOTE_SORT'
export const SET_CHARACTER_FILTER = 'SET_CHARACTER_FILTER'
export const SET_PLACE_FILTER = 'SET_PLACE_FILTER'
export const SET_NOTE_FILTER = 'SET_NOTE_FILTER'
export const NAVIGATE_TO_BOOK_TIMELINE = 'NAVIGATE_TO_BOOK_TIMELINE'
export const EXPAND_TIMELINE = 'EXPAND_TIMELINE'
export const COLLAPSE_TIMELINE = 'COLLAPSE_TIMELINE'
export const SET_TIMELINE_FILTER = 'SET_TIMELINE_FILTER'
export const CLEAR_TEMPLATE_FROM_TIMELINE = 'CLEAR_TEMPLATE_FROM_TIMELINE'
export const RESET_TIMELINE = 'RESET_TIMELINE'
export const RECORD_SCROLL_POSITION = 'RECORD_SCROLL_POSITION'
export const OPEN_ATTRIBUTES_DIALOG = 'OPEN_ATTRIBUTES_DIALOG'
export const CLOSE_ATTRIBUTES_DIALOG = 'CLOSE_ATTRIBUTES_DIALOG'
export const SET_TIMELINE_SIZE = 'SET_TIMELINE_SIZE'
export const SET_OUTLINE_FILTER = 'SET_OUTLINE_FILTER'

// beat actions
export const ADD_BEAT = 'ADD_BEAT'
export const EDIT_BEAT_TITLE = 'EDIT_BEAT_TITLE'
export const REORDER_BEATS = 'REORDER_BEATS'
export const DELETE_BEAT = 'DELETE_BEAT'
export const AUTO_SORT_BEAT = 'AUTO_SORT_BEAT'
export const INSERT_BEAT = 'INSERT_BEAT'
export const EXPAND_BEAT = 'EXPAND_BEAT'
export const COLLAPSE_BEAT = 'COLLAPSE_BEAT'

// card actions
export const ADD_CARD = 'ADD_CARD'
export const ADD_CARD_IN_BEAT = 'ADD_CARD_IN_BEAT'
export const EDIT_CARD_DETAILS = 'EDIT_CARD_DETAILS'
export const EDIT_CARD_TEMPLATE_ATTRIBUTES = 'EDIT_CARD_TEMPLATE_ATTRIBUTES'
export const EDIT_CARD_COORDINATES = 'EDIT_CARD_COORDINATES'
export const DELETE_CARD = 'DELETE_CARD'
export const CHANGE_LINE = 'CHANGE_STORYLINE'
export const CHANGE_BEAT = 'CHANGE_BEAT'
export const CHANGE_BOOK = 'CHANGE_BOOK'
export const REORDER_CARDS_WITHIN_LINE = 'REORDER_CARDS_WITHIN_LINE'
export const REORDER_CARDS_IN_BEAT = 'REORDER_CARDS_IN_BEAT'

export const ATTACH_CHARACTER_TO_CARD = 'ATTACH_CHARACTER_TO_CARD'
export const ATTACH_PLACE_TO_CARD = 'ATTACH_PLACE_TO_CARD'
export const ATTACH_TAG_TO_CARD = 'ATTACH_TAG_TO_CARD'
export const REMOVE_CHARACTER_FROM_CARD = 'REMOVE_CHARACTER_FROM_CARD'
export const REMOVE_PLACE_FROM_CARD = 'REMOVE_PLACE_FROM_CARD'
export const REMOVE_TAG_FROM_CARD = 'REMOVE_TAG_FROM_CARD'

// line actions
export const ADD_LINE = 'ADD_STORYLINE'
export const ADD_LINE_WITH_TITLE = 'ADD_LINE_WITH_TITLE'
export const ADD_LINES_FROM_TEMPLATE = 'ADD_LINES_FROM_TEMPLATE'
export const EDIT_LINE = 'EDIT_LINE'
export const EDIT_LINE_TITLE = 'EDIT_STORYLINE_TITLE'
export const EDIT_LINE_COLOR = 'EDIT_STORYLINE_COLOR'
export const REORDER_LINES = 'REORDER_STORYLINES'
export const DELETE_LINE = 'DELETE_STORYLINE'
export const EXPAND_LINE = 'EXPAND_LINE'
export const COLLAPSE_LINE = 'COLLAPSE_LINE'

// places actions
export const ADD_PLACE = 'ADD_PLACE'
export const ADD_PLACE_WITH_VALUES = 'ADD_PLACE_WITH_VALUES'
export const EDIT_PLACE = 'EDIT_PLACE'
export const DELETE_PLACE = 'DELETE_PLACE'
export const ATTACH_TAG_TO_PLACE = 'ATTACH_TAG_TO_PLACE'
export const ATTACH_BOOK_TO_PLACE = 'ATTACH_BOOK_TO_PLACE'
export const REMOVE_TAG_FROM_PLACE = 'REMOVE_TAG_FROM_PLACE'
export const REMOVE_BOOK_FROM_PLACE = 'REMOVE_BOOK_FROM_PLACE'

// tags actions
export const ADD_TAG = 'ADD_TAG'
export const ADD_TAG_WITH_VALUES = 'ADD_TAG_WITH_VALUES'
export const ADD_CREATED_TAG = 'ADD_CREATED_TAG'
export const EDIT_TAG = 'EDIT_TAG'
export const CHANGE_TAG_COLOR = 'CHANGE_TAG_COLOR'
export const DELETE_TAG = 'DELETE_TAG'

// characters actions
export const ADD_CHARACTER = 'ADD_CHARACTER'
export const ADD_CHARACTER_WITH_TEMPLATE = 'ADD_CHARACTER_WITH_TEMPLATE'
export const ADD_CHARACTER_WITH_VALUES = 'ADD_CHARACTER_WITH_VALUES'
export const EDIT_CHARACTER = 'EDIT_CHARACTER'
export const DELETE_CHARACTER = 'DELETE_CHARACTER'
export const ATTACH_TAG_TO_CHARACTER = 'ATTACH_TAG_TO_CHARACTER'
export const ATTACH_BOOK_TO_CHARACTER = 'ATTACH_BOOK_TO_CHARACTER'
export const REMOVE_TAG_FROM_CHARACTER = 'REMOVE_TAG_FROM_CHARACTER'
export const REMOVE_BOOK_FROM_CHARACTER = 'REMOVE_BOOK_FROM_CHARACTER'

// notes actions
export const ADD_NOTE = 'ADD_NOTE'
export const EDIT_NOTE = 'EDIT_NOTE'
export const DELETE_NOTE = 'DELETE_NOTE'

export const ATTACH_CHARACTER_TO_NOTE = 'ATTACH_CHARACTER_TO_NOTE'
export const ATTACH_PLACE_TO_NOTE = 'ATTACH_PLACE_TO_NOTE'
export const ATTACH_TAG_TO_NOTE = 'ATTACH_TAG_TO_NOTE'
export const ATTACH_BOOK_TO_NOTE = 'ATTACH_BOOK_TO_NOTE'
export const REMOVE_CHARACTER_FROM_NOTE = 'REMOVE_CHARACTER_FROM_NOTE'
export const REMOVE_PLACE_FROM_NOTE = 'REMOVE_PLACE_FROM_NOTE'
export const REMOVE_TAG_FROM_NOTE = 'REMOVE_TAG_FROM_NOTE'
export const REMOVE_BOOK_FROM_NOTE = 'REMOVE_BOOK_FROM_NOTE'

// custom attribute actions
export const ADD_CHARACTER_ATTRIBUTE = 'ADD_CHARACTER_ATTRIBUTE'
export const ADD_PLACES_ATTRIBUTE = 'ADD_PLACES_ATTRIBUTE'
export const ADD_CARDS_ATTRIBUTE = 'ADD_CARDS_ATTRIBUTE'
export const ADD_LINES_ATTRIBUTE = 'ADD_LINES_ATTRIBUTE'
export const ADD_NOTES_ATTRIBUTE = 'ADD_NOTES_ATTRIBUTE'

export const REMOVE_CHARACTER_ATTRIBUTE = 'REMOVE_CHARACTER_ATTRIBUTE'
export const REMOVE_PLACES_ATTRIBUTE = 'REMOVE_PLACES_ATTRIBUTE'
export const REMOVE_CARDS_ATTRIBUTE = 'REMOVE_CARDS_ATTRIBUTE'
export const REMOVE_LINES_ATTRIBUTE = 'REMOVE_LINES_ATTRIBUTE'
export const REMOVE_NOTES_ATTRIBUTE = 'REMOVE_NOTES_ATTRIBUTE'

export const EDIT_CHARACTER_ATTRIBUTE = 'EDIT_CHARACTER_ATTRIBUTE'
export const EDIT_PLACES_ATTRIBUTE = 'EDIT_PLACES_ATTRIBUTE'
export const EDIT_CARDS_ATTRIBUTE = 'EDIT_CARDS_ATTRIBUTE'
export const EDIT_LINES_ATTRIBUTE = 'EDIT_LINES_ATTRIBUTE'
export const EDIT_NOTES_ATTRIBUTE = 'EDIT_NOTES_ATTRIBUTE'

export const REORDER_CHARACTER_ATTRIBUTE = 'REORDER_CHARACTER_ATTRIBUTE'
export const REORDER_PLACES_ATTRIBUTE = 'REORDER_PLACES_ATTRIBUTE'
export const REORDER_CARDS_ATTRIBUTE = 'REORDER_CARDS_ATTRIBUTE'
export const REORDER_LINES_ATTRIBUTE = 'REORDER_LINES_ATTRIBUTE'
export const REORDER_NOTES_ATTRIBUTE = 'REORDER_NOTES_ATTRIBUTE'

// image actions
export const ADD_IMAGE = 'ADD_IMAGE'
export const RENAME_IMAGE = 'RENAME_IMAGE'
export const DELETE_IMAGE = 'DELETE_IMAGE'

// series actions
export const EDIT_SERIES = 'EDIT_SERIES'

// book actions
export const ADD_BOOK = 'ADD_BOOK'
export const EDIT_BOOK = 'EDIT_BOOK'
export const DELETE_BOOK = 'DELETE_BOOK'
export const REORDER_BOOKS = 'REORDER_BOOKS'

// category actions
export const ADD_CHARACTER_CATEGORY = 'ADD_CHARACTER_CATEGORY'
export const DELETE_CHARACTER_CATEGORY = 'DELETE_CHARACTER_CATEGORY'
export const UPDATE_CHARACTER_CATEGORY = 'UPDATE_CHARACTER_CATEGORY'
export const REORDER_CHARACTER_CATEGORY = 'REORDER_CHARACTER_CATEGORY'
export const ADD_NOTE_CATEGORY = 'ADD_NOTE_CATEGORY'
export const DELETE_NOTE_CATEGORY = 'DELETE_NOTE_CATEGORY'
export const UPDATE_NOTE_CATEGORY = 'UPDATE_NOTE_CATEGORY'
export const REORDER_NOTE_CATEGORY = 'REORDER_NOTE_CATEGORY'
export const ADD_TAG_CATEGORY = 'ADD_TAG_CATEGORY'
export const DELETE_TAG_CATEGORY = 'DELETE_TAG_CATEGORY'
export const UPDATE_TAG_CATEGORY = 'UPDATE_TAG_CATEGORY'
export const REORDER_TAG_CATEGORY = 'REORDER_TAG_CATEGORY'

// hierarchy actions
export const SET_HIERARCHY_LEVELS = 'SET_HIERARCHY_LEVELS'
export const EDIT_HIERARCHY_LEVEL = 'EDIT_HIERARCHY_LEVEL'

// feature flags
export const SET_FEATURE_FLAG = 'SET_FEATURE_FLAG'
export const UNSET_FEATURE_FLAG = 'UNSET_FEATURE_FLAG'

// tour actions
export const SET_TOUR_FEATURE = 'SET_TOUR_FEATURE'
export const TOUR_NEXT = 'TOUR_NEXT'
export const TOUR_RESTART = 'TOUR_RESTART'
