export const FILE_LOADED = 'FILE_LOADED'
export const FILE_SAVED = 'FILE_SAVED'
export const NEW_FILE = 'NEW_FILE'
export const CHANGE_CURRENT_VIEW = 'CHANGE_CURRENT_VIEW'
export const CHANGE_ORIENTATION = 'CHANGE_ORIENTATION'
export const RESET = 'RESET'

// story actions
export const EDIT_STORY_NAME = 'EDIT_STORY_NAME'

// scene actions
export const ADD_SCENE = 'ADD_SCENE'
export const EDIT_SCENE_TITLE = 'EDIT_SCENE_TITLE'
export const REORDER_SCENES = 'REORDER_SCENES'
export const DELETE_SCENE = 'DELETE_SCENE'

// card actions
export const ADD_CARD = 'ADD_CARD'
export const EDIT_CARD_DETAILS = 'EDIT_CARD_DETAILS'
export const EDIT_CARD_COORDINATES = 'EDIT_CARD_COORDINATES'
export const DELETE_CARD = 'DELETE_CARD'
export const CHANGE_LINE = 'CHANGE_STORYLINE'
export const CHANGE_SCENE = 'CHANGE_SCENE'

export const ATTACH_CHARACTER_TO_CARD = 'ATTACH_CHARACTER_TO_CARD'
export const ATTACH_PLACE_TO_CARD = 'ATTACH_PLACE_TO_CARD'
export const ATTACH_TAG_TO_CARD = 'ATTACH_TAG_TO_CARD'
export const REMOVE_CHARACTER_FROM_CARD = 'REMOVE_CHARACTER_FROM_CARD'
export const REMOVE_PLACE_FROM_CARD = 'REMOVE_PLACE_FROM_CARD'
export const REMOVE_TAG_FROM_CARD = 'REMOVE_TAG_FROM_CARD'

// line actions
export const ADD_LINE = 'ADD_STORYLINE'
export const EDIT_LINE_TITLE = 'EDIT_STORYLINE_TITLE'
export const EDIT_LINE_COLOR = 'EDIT_STORYLINE_COLOR'
export const REORDER_LINES = 'REORDER_STORYLINES'
export const DELETE_LINE = 'DELETE_STORYLINE'

// places actions
export const ADD_PLACE = 'ADD_PLACE'
export const EDIT_PLACE = 'EDIT_PLACE'
export const DELETE_PLACE = 'DELETE_PLACE'

// tags actions
export const ADD_TAG = 'ADD_TAG'
export const EDIT_TAG = 'EDIT_TAG'
export const DELETE_TAG = 'DELETE_TAG'

// characters actions
export const ADD_CHARACTER = 'ADD_CHARACTER'
export const EDIT_CHARACTER = 'EDIT_CHARACTER'
export const DELETE_CHARACTER = 'DELETE_CHARACTER'

// notes actions
export const ADD_NOTE = 'ADD_NOTE'
export const EDIT_NOTE = 'EDIT_NOTE'
export const DELETE_NOTE = 'DELETE_NOTE'

export const ATTACH_CHARACTER_TO_NOTE = 'ATTACH_CHARACTER_TO_NOTE'
export const ATTACH_PLACE_TO_NOTE = 'ATTACH_PLACE_TO_NOTE'
export const ATTACH_TAG_TO_NOTE = 'ATTACH_TAG_TO_NOTE'
export const REMOVE_CHARACTER_FROM_NOTE = 'REMOVE_CHARACTER_FROM_NOTE'
export const REMOVE_PLACE_FROM_NOTE = 'REMOVE_PLACE_FROM_NOTE'
export const REMOVE_TAG_FROM_NOTE = 'REMOVE_TAG_FROM_NOTE'

// custom attribute actions
export const ADD_CHARACTER_ATTRIBUTE = 'ADD_CHARACTER_ATTRIBUTE'
export const ADD_PLACES_ATTRIBUTE = 'ADD_PLACES_ATTRIBUTE'
export const ADD_CARDS_ATTRIBUTE = 'ADD_CARDS_ATTRIBUTE'
export const ADD_LINES_ATTRIBUTE = 'ADD_LINES_ATTRIBUTE'
export const ADD_SCENES_ATTRIBUTE = 'ADD_SCENES_ATTRIBUTE'

export const REMOVE_CHARACTER_ATTRIBUTE = 'REMOVE_CHARACTER_ATTRIBUTE'
export const REMOVE_PLACES_ATTRIBUTE = 'REMOVE_PLACES_ATTRIBUTE'
export const REMOVE_CARDS_ATTRIBUTE = 'REMOVE_CARDS_ATTRIBUTE'
export const REMOVE_LINES_ATTRIBUTE = 'REMOVE_LINES_ATTRIBUTE'
export const REMOVE_SCENES_ATTRIBUTE = 'REMOVE_SCENES_ATTRIBUTE'
