osx_image: xcode10.2
os: osx
language: node_js
node_js: '10'
env:
  - ELECTRON_CACHE=$HOME/.electron
cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
script:
  - npm run dist
branches:
  only:
    - master
