import { connect } from 'react-redux'
import { bindActionCreators } from 'redux'
import * as pltr from 'pltr/v2'
import {
  OverlayTrigger,
  DeleteConfirmModal,
  ColorPickerColor,
  ItemsManagerModal as UnconnectedItemsManagerModal,
  ListItem,
  PlottrModal as UnconnectedPlottrModal,
  EditAttribute as UnconnectedEditAttribute,
  FilterList as UnconnectedFilterList,
  RichText as UnconnectedRichText,
  editorRegistry,
  normalize,
  Image as UnconnectedImage,
  ImagePicker as UnconnectedImagePicker,
  MiniColorPicker,
  Spinner,
  FunSpinner,
  InputModal,
  ColorPicker as UnconnectedColorPicker,
  Switch,
  CardTemplateDetails,
  PlotlineTemplateDetails as UnconnectedPlotlineTemplateDetails,
  TemplateCreate as UnconnectedTemplateCreate,
  TemplateEdit,
  TemplatePicker as UnconnectedTemplatePicker,
  Beamer as UnconnectedBeamer,
  LanguagePicker as UnconnectedLanguagePicker,
  CategoryPicker as UnconnectedCategoryPicker,
  CharacterCategoriesModal as UnconnectedCharacterCategoriesModal,
  CharacterDetails as UnconnectedCharacterDetails,
  CharacterEditDetails as UnconnectedCharacterEditDetails,
  CharacterItem as UnconnectedCharacterItem,
  CharacterListView as UnconnectedCharacterListView,
  CustomAttrFilterList as UnconnectedCustomAttrFilterList,
  BookFilterList as UnconnectedBookFilterList,
  CharacterCategoryFilterList as UnconnectedCharacterCategoryFilterList,
  CharactersFilterList as UnconnectedCharactersFilterList,
  PlacesFilterList as UnconnectedPlacesFilterList,
  TagFilterList as UnconnectedTagFilterList,
  GenericFilterList,
  CardColorFilterList,
  SortList as UnconnectedSortList,
  CharacterView as UnconnectedCharacterView,
  BookSelectList as UnconnectedBookSelectList,
  BookList as UnconnectedBookList,
  EditSeries as UnconnectedEditSeries,
  FileLocation as UnconnectedFileLocation,
  BookChooser as UnconnectedBookChooser,
  TagView as UnconnectedTagView,
  TagListView as UnconnectedTagListView,
  ExportDialog as UnconnectedExportDialog,
  ExportNavItem as UnconnectedExportNavItem,
  NoteListView as UnconnectedNoteListView,
  OutlineView as UnconnectedOutlineView,
  PlaceListView as UnconnectedPlaceListView,
  TimelineWrapper as UnconnectedTimelineWrapper,
  ActsConfigModal as UnconnectedActsConfigModal,
  AskToSaveModal,
  ErrorBoundary as UnconnectedErrorBoundary,
  DashboardErrorBoundary as UnconnectedDashboardErrorBoundary,
  SelectList as UnconnectedSelectList,
  TagLabel,
  CustomAttributeModal as UnconnectedCustomAttributeModal,
  SubNav as UnconnectedSubNav,
  ProjectTemplateDetails,
  CharacterTemplateDetails,
  DashboardBody as UnconnectedDashboardBody,
} from '../components'

const connector = {
  redux: {
    connect,
    bindActionCreators,
  },
  pltr,
}

// Platform is an object which provides features which are specific to
// a given platform.  For example, opening a file or a URL.
//
// It should provide the following functions:
// {
//   electron: Object?,
//   openExternal: (Url) => IO,
//   log: {
//     info: (String) => IO,
//     error: (String) => IO,
//     warn: (String) => IO,
//   },
//   updateLanguage: String => IO,
//   license: {
//     licenseStore: { clear: () => IO },
//     checkForActiveLicense: (Object, (object, object) => IO) => IO
//     useLicenseInfo: () => [Object, number],
//     useTrialStatus: () => { started: bool, expired: bool, startTrial: Number => IO },
//     verifyLicense: (Object, (bool, Object) => IO) => IO,
//     trial90days: { includes: Object => bool },
//   },
//   reloadMenu: () => IO,
//   checkForUpdates: () => IO,
//   dialog: {
//     showErrorBox: (string, string) => IO,
//   }
//   showSaveDialogSync,
//   showOpenDialogSync,
//   createErrorReport: (String) => IO,
//   appVersion: String,
//   defaultBackupLocation,
//   setDarkMode,
//   file: {
//     createNew: Object => IO,
//     openExistingFile: () => IO,
//     openKnownFile: (String, String) => IO,
//     doesFileExist: String => IO bool,
//     useSortedKnownFiles: () => [[String], { String => Object }],
//     isTempFile: String => bool,
//     pathSep: String,
//     basename: String => String,
//     deleteKnownFile: (String, String) => IO,
//     editKnownFilePath: (String, String) => IO,
//     removeFromKnownFiles: String => IO,
//     saveFile: (String, Object) => IO,
//     readFileSync: (String, String) => IO,
//     createFromSnowflake: (String) => IO,
//     joinPath: (*String) => String,
//   },
//   update: {
//     onUpdateError: (Object, Object) => IO,
//     onUpdaterUpdateAvailable: (Object, Object) => IO,
//     onUpdaterUpdateNotAvailable: () => IO,
//     onUpdaterDownloadProgress: (Object, Object) => IO,
//     onUpdatorUpdateDownloaded: (Object, Object) => IO,
//     checkForUpdates: () => IO,
//     downloadUpdate: () => IO,
//     quitToInstall: () => IO,
//   }
//   template: {
//     TemplateFetcher: Class,
//     listTemplates,
//     listCustomTemplates,
//     deleteTemplate,
//     editTemplateDetails,
//     startSaveAsTemplate,
//     saveTemplate,
//     useFilteredSortedTemplates: () => Object,
//     useCustomTemplatesInfo: () => [Object],
//     useTemplatesInfo: () => [Object]
//   },
//   electron?: Electron,
//   settings: {
//     get: String => Any
//   },
//   useSettingsInfo: () => [Object, Any, (String, Any) => IO],
//   user: {
//     get: String => Any
//   },
//   os: string,
//   isDevelopment: bool,
//   isWindows: bool,
//   isMacOs: bool,
//   node: {
//     env: string,
//   }
//   rollbar: {
//     rollbarAccessToken: string,
//     platform: string,
//   }
//   export: {
//     askToExport: (string, object, string, object, (Error, boolean) => IO),
//     export_config: object,
//   }
//   store: {
//     useExportConfigInfo: hook,
//   }
//   useBackupFolders: () => [String],
//   moveFromTemp: () => IO,
//   moveItemToTrash: String  => IO,
//   showItemInFolder: String => IO,
//   tempFilesPath: String
//   mpq: {
//     push: String => IO
//   }
//   inBrowser: bool,
//   browserHistory: object,
//   templatesDisabled: bool,
//   rootElementSelectors: [String],
//   machineIdSync: () => IO String,
// }

export default (platform) => {
  var connectorObject = { ...connector, platform }
  return {
    OverlayTrigger,
    DeleteConfirmModal,
    ColorPickerColor,
    ItemsManagerModal: UnconnectedItemsManagerModal(connectorObject),
    ListItem,
    PlottrModal: UnconnectedPlottrModal(connectorObject),
    EditAttribute: UnconnectedEditAttribute(connectorObject),
    FilterList: UnconnectedFilterList(connectorObject),
    RichText: UnconnectedRichText(connectorObject),
    editorRegistry,
    normalize,
    Image: UnconnectedImage(connectorObject),
    ImagePicker: UnconnectedImagePicker(connectorObject),
    MiniColorPicker,
    Spinner,
    FunSpinner,
    InputModal,
    ColorPicker: UnconnectedColorPicker(connectorObject),
    Switch,
    CardTemplateDetails,
    PlotlineTemplateDetails: UnconnectedPlotlineTemplateDetails(connectorObject),
    TemplateCreate: UnconnectedTemplateCreate(connectorObject),
    TemplateEdit,
    TemplatePicker: UnconnectedTemplatePicker(connectorObject),
    Beamer: UnconnectedBeamer(connectorObject),
    LanguagePicker: UnconnectedLanguagePicker(connectorObject),
    CategoryPicker: UnconnectedCategoryPicker(connectorObject),
    CharacterCategoriesModal: UnconnectedCharacterCategoriesModal(connectorObject),
    CharacterDetails: UnconnectedCharacterDetails(connectorObject),
    CharacterEditDetails: UnconnectedCharacterEditDetails(connectorObject),
    CharacterItem: UnconnectedCharacterItem(connectorObject),
    CharacterListView: UnconnectedCharacterListView(connectorObject),
    CustomAttrFilterList: UnconnectedCustomAttrFilterList(connectorObject),
    BookFilterList: UnconnectedBookFilterList(connectorObject),
    CharacterCategoryFilterList: UnconnectedCharacterCategoryFilterList(connectorObject),
    CharactersFilterList: UnconnectedCharactersFilterList(connectorObject),
    PlacesFilterList: UnconnectedPlacesFilterList(connectorObject),
    TagFilterList: UnconnectedTagFilterList(connectorObject),
    GenericFilterList,
    CardColorFilterList,
    SortList: UnconnectedSortList(connectorObject),
    CharacterView: UnconnectedCharacterView(connectorObject),
    BookSelectList: UnconnectedBookSelectList(connectorObject),
    BookList: UnconnectedBookList(connectorObject),
    EditSeries: UnconnectedEditSeries(connectorObject),
    FileLocation: UnconnectedFileLocation(connectorObject),
    BookChooser: UnconnectedBookChooser(connectorObject),
    TagView: UnconnectedTagView(connectorObject),
    TagListView: UnconnectedTagListView(connectorObject),
    ExportDialog: UnconnectedExportDialog(connectorObject),
    ExportNavItem: UnconnectedExportNavItem(connectorObject),
    NoteListView: UnconnectedNoteListView(connectorObject),
    OutlineView: UnconnectedOutlineView(connectorObject),
    PlaceListView: UnconnectedPlaceListView(connectorObject),
    TimelineWrapper: UnconnectedTimelineWrapper(connectorObject),
    ActsConfigModal: UnconnectedActsConfigModal(connectorObject),
    AskToSaveModal,
    ErrorBoundary: UnconnectedErrorBoundary(connectorObject),
    DashboardErrorBoundary: UnconnectedDashboardErrorBoundary(connectorObject),
    SelectList: UnconnectedSelectList(connectorObject),
    TagLabel,
    CustomAttributeModal: UnconnectedCustomAttributeModal(connectorObject),
    SubNav: UnconnectedSubNav(connectorObject),
    ProjectTemplateDetails,
    CharacterTemplateDetails,
    DashboardBody: UnconnectedDashboardBody(connectorObject),
  }
}
