module.exports = {
  showTheTour: false,
  backup: true,
  allowPrerelease: false,
  forceDevTools: false,
  trialMode: false,
  canGetUpdates: true,
  isInGracePeriod: false,
  gracePeriodEnd: 0,
  canEdit: true,
  canExport: true,
  user: {
    autoDownloadUpdate: true,
    autoSave: true,
    backupDays: 30,
    backupLocation: 'default',
    dark: 'system',
    themeSource: 'system',
    numberOfBackups: 30,
    backupType: 'never-delete',
    localBackups: false,
    openDashboardFirst: true,
    enableOfflineMode: false,
    streamFriendly: false,
    useSpellcheck: true,
    font: 'Forum',
    fontSize: 20,
  },
}
